### ISSUE TITLE
cannot import name 'TrueBetaDistribution' from 'pomegranate

### ISSUE THREAD

**Issue by shicaiwei123** [hhc1997/L2RM#1]
Hello， thanks for your excellent work.

 Now I try to run the code however, I encounter some errors.

I got the error as follows, 
Traceback (most recent call last):
  File "/home/bbb/shicaiwei/L2RM/grammar_test.py", line 2, in <module>
    from pomegranate import GeneralMixtureModel,TrueBetaDistribution
ImportError: cannot import name 'TrueBetaDistribution' from 'pomegranate' (/home/bbb/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/pomegranate-0.14.8-py3.8-linux-x86_64.egg/pomegranate/__init__.py)

The version of the pomegranate I used is 0.14.8.  I guess that may be caused by the version. Could you tell me what's version  you used?

**Comment by hhc1997** [comment]
Hello, @shicaiwei123.  The official pomegranate does not integrate the module `TrueBetaDistribution`. You need to install the version provided by [rayleizhu](https://github.com/rayleizhu/pomegranate).  You need to install `Cython=0.29`, `NumPy`, `SciPy`, `NetworkX`, and `joblib` first. Then you can run `python setup.py build` and `python setup.py install` to install it.

**Comment by shicaiwei123** [comment]
Thanks for your reply, it does work. However, I encounter another problem when I reproduce the performance in the paper.

Specifically, the performance I reproduced is lower than that in the paper. The results on Flickr30K are as follows,

noisy=0.2

-----------------SAF------------------
rsum: 487.4
Average i2t Recall: 87.8
Image to text: 74.2 92.7 96.4 1.0 3.4
Average t2i Recall: 74.7
Text to image: 55.0 81.1 88.0 1.0 9.5
---------------------------------------
-----------------SGR------------------
rsum: 493.5
Average i2t Recall: 88.9
Image to text: 75.3 94.0 97.3 1.0 2.3
Average t2i Recall: 75.6
Text to image: 56.4 81.9 88.5 1.0 17.3
---------------------------------------
-----------------SGRAF------------------
rsum: 498.6
Average i2t Recall: 89.3
Image to text: 76.2 94.3 97.4 1.0 2.9
Average t2i Recall: 76.9
Text to image: 58.0 83.2 89.4 1.0 8.9
---------------------------------------





noisy=0.6
-----------------SAF------------------
rsum: 447.3
Average i2t Recall: 81.9
Image to text: 64.1 88.1 93.6 1.0 4.6
Average t2i Recall: 67.2
Text to image: 46.6 73.1 81.8 2.0 15.9
---------------------------------------
-----------------SGR------------------
rsum: 444.4
Average i2t Recall: 81.1
Image to text: 64.2 86.7 92.3 1.0 4.6
Average t2i Recall: 67.1
Text to image: 46.2 73.3 81.7 2.0 16.1
---------------------------------------
-----------------SGRAF------------------
rsum: 460.3
Average i2t Recall: 83.7
Image to text: 67.3 89.3 94.4 1.0 4.2
Average t2i Recall: 69.8
Text to image: 49.3 76.3 83.7 2.0 14.4
---------------------------------------


I also tried the provided pretrained model, however, I got the following error:
AttributeError: 'Namespace' object has no attribute 'reg'

It seems like the SGARF model in the provided pretrained model does not contain the variable reg and rho, which are used in the forward in line 1110 in model.py. 

So how do you set these parameters in the pretrained model? Maybe this is the key to performance

**Comment by hhc1997** [comment]
Hello, @shicaiwei123 
① The Sinkhorn regularization is set as 0.01, 0.01, and 0.07 for Flickr30K, MSCOCO, and CC152K.  The partial transport mass rho is set to 0.1 for all experiments. 
②  Our method seeks refined alignments for mismatched pairs in every minibatch. So I suggest you use different random seeds for SGR model and SAF model. For the provided pretrained model, we set the  `opt.seed` as 42 and 3407 for SGR and SAF, respectively. 
③ The pretrained model does not contain `opt.reg` and `opt.rho` because we directly fix these parameters in the previous version. You can run `main_testing.py ` with the provided pertained models, and it seems the AttributeError would not occur. For example, for 0.2 noisy setting:

-----------------SAF------------------
rsum: 492.4
Average i2t Recall: 88.6
Image to text: 73.7 94.3 97.7 1.0 3.0
Average t2i Recall: 75.6
Text to image: 56.8 81.8 88.1 1.0 8.7
---------------------------------------
-----------------SGR------------------
rsum: 492.5
Average i2t Recall: 89.2
Image to text: 76.5 93.7 97.3 1.0 2.8
Average t2i Recall: 75.0
Text to image: 55.5 81.5 88.0 1.0 8.5
---------------------------------------
-----------------SGRAF------------------
rsum: 503.8
Average i2t Recall: 90.3
Image to text: 77.9 95.2 97.8 1.0 2.8
Average t2i Recall: 77.6
Text to image: 59.8 83.6 89.5 1.0 8.2
---------------------------------------
